### ISSUE TITLE
S-58 Check 44 - Amend to allow DRVAL1 and/or DRVAL2 to equal values other than the DEPCNT.VALDCO found within the ENC 

### ISSUE THREAD

**Issue by iho-ohi** [iho-ohi/ENCWG-S58-ENC-Validation-Checks#2]
Proposal from Nautical Dimensions
The current check 44 triggers when the DRVAL1 or DRVAL2 of a DEPARE (apart from the shallowest and deepest found in the cell) contains a value that is not equal to the value of VALDCO on a DEPCNT feature object found within the cell.
Some producers encode DRVAL1 with the shallowest depth within a shoal. For example, a shoal with DRVAL1 = 4.6 and DRVAL2 = 5. The values of VALDCO are 0, 2, 5, 10, ... (see attached document for proposed check wording.
[S58-Check 44.docx](https://github.com/iho-ohi/ENCWG-S58-ENC-Validation-Checks/files/5108137/S58-Check.44.docx)

**Comment by FrankHippmann** [comment]
Agree

**Comment by TomRichardson6** [comment]
Agree

**Comment by alvarosanuy** [comment]
I think there's a pending ENCWG action to review/amend the content of the UOC in regards to the encoding of DRVAL1 for 'isolated shoals".
The use of a DRVAL1 value that matches the shoalest depth within a shoal is not recommended as it will cause problems when this depth is equal to VALDCO. A DEPARE can't have DRVAL1=DRVAL2. A possible work around is to encode DRVAL1 with a value that is 10cm (0.1m) shoaler than the shoalest depth.
This check may need to wait until the UOC is updated but I'd recommend considering the following changes to Check 44b:

![image](https://user-images.githubusercontent.com/70189016/95156772-14087000-07e3-11eb-80bf-08db2fd7c7cf.png)

**Comment by Richard-Fowle** [comment]
I agree with Alvaro that this proposal should await the outcome of the ENCWG action to review/amend UOC 5.4.3. 
It should also be that the paper from Nautical Dimensions also proposes adding a definition for a shoal within S-58, as the only definitions in S-58 are those for Geometric Operators, this may require some restructuring of section 1

**Comment by Christian-Shom** [comment]
Agree to wait until further discussion within the ENCWG.
Agree with Richard comment on operators in S-58. I'm not sure adding a "UOC" definition of a shoal (that is not in line with those in S-32) is a good thing. There are "local shallow area bounded by a single depth contour" of very large dimensions...

**Comment by JeffWootton** [comment]
Agree with all the above.

**Comment by FrankHippmann** [comment]
I agree with Christian's comment regarding shoals. Perhaps the UOC review and the resulting S-58 check shouldn't refer to a shoal in this instance, but rather a "local shallow area".

Can a similar argument could be made regarding the encoding of DRVAL2 and "local deep areas"?

**Comment by IngaFjellanger** [comment]
Agree to postpone this.

Is it possible to have different -H values inside a cell according to the standard? In real world that could very well happen, particularly if it the scale is medium or small.

We should also take into consideration that in many ENCs the -H is not known.

**Comment by FrankHippmann** [comment]
Following ENCWG VTC3, I have updated the proposal for S-58 check 44. In addition, proposals for the related checks 1768a and 1779 have been made.

[S-58 checks 44, 1768a and 1779.docx](https://github.com/iho-ohi/ENCWG-S58-ENC-Validation-Checks/files/6020080/S-58.checks.44.1768a.and.1779.docx)
[ENCWGVTC3_2021_09.f_EN_DRVAL1 and DRVAL2 for isolated shallow and deep areas_V1.pdf](https://github.com/iho-ohi/ENCWG-S58-ENC-Validation-Checks/files/6020081/ENCWGVTC3_2021_09.f_EN_DRVAL1.and.DRVAL2.for.isolated.shallow.and.deep.areas_V1.pdf)
