### ISSUE TITLE
S-58 Check 2000 attribute STATUS

### ISSUE THREAD

**Issue by iho-ohi** [iho-ohi/ENCWG-S58-ENC-Validation-Checks#22]
Proposal from DK to address an inconsistency between the allowable values for the attributes STATUS for Bouys and Beacons and that for TOPMAR feature objects.

[S58-Check 2000 -STATUS.docx](https://github.com/iho-ohi/ENCWG-S58-ENC-Validation-Checks/files/5116658/S58-Check.2000.-STATUS.docx)

**Comment by FrankHippmann** [comment]
I don't necessarily disagree. but the topmark is logically a part of the buoy/beacon. The topmark logically doesn’t exist without the buoy/beacon. If the buoy/beacon is occasional, it is implied that the topmark is also occasional. We should, therefore, avoid duplicating the attribute encoding of the buoy/beacon on the topmark. If we say the topmark is occasional, this could be interpreted as the buoy/beacon sometimes having the topmark and sometimes not.

**Comment by IngaFjellanger** [comment]
Navoci agrees with suggestion from DK

**Comment by alvarosanuy** [comment]
Not sure why DK is pursuing these changes. The only reason I can think of is that DK came across some other S-58 check that reports discrepancies between attribute values among features in an object/equipment relationship.
To be honest there are more merits to remove attribute values from the list than to add.
I think STATUS for buoys should be reduced to 4 & 7 and for beacons to 4,7 & 12.
The idea of matching BOY* and BCN* STATUS values to TOPMAR STATUS values does not bring any benefits. None of them trigger portrayal and the 'logical consistency' argument is arguable. 
If we update STATUS values for BOY* and BCN* we may also need to revisit DAYMAR's  ………… which may play the 'equipment' role when located on beacons.
The only reason could be that there's another S-58 check trying to correlate attribute values between object/equipment relationships

**Comment by TomRichardson6** [comment]
Do not support this change. Propose that general changes to check 2000 should also consider data modelling in S-101 so propose a future activity to review check 2000 and possibly create a check 2001 for S-101 pre-compliance but only to be published once S-101 reaches 2.0.0.

**Comment by JeffWootton** [comment]
I do not support this change.  In general, I agree with the comments from Alvaro and Tom.  I question how an encoded buoy or beacon could be “existence doubtful”, and why “occasional” is not “periodic/intermittent” (?).  For this reason I would perhaps look at the allowable values for STATUS on buoys and beacons instead.

**Comment by Christian-Shom** [comment]
We do have some buoys encoded as "occasional". Others may have different "exotic" encodings.
On the whole, I think there is nothing really importnat for navigation.
Suggest to leave Checks as they are for S-57, and surely review for S-101 to concentrate on values useful for the mariner.

**Comment by LARRIVEEJCANADA** [comment]
Not agree, this is taking in account with the Buoy shape as the TOPMAR is not really existing in stand alone.  This is not a critical information and a coding duplication.
