### ISSUE TITLE
S-58 New check for missing centre point for LIGHTS with range > 10M

### ISSUE THREAD

**Issue by iho-ohi** [iho-ohi/ENCWG-S58-ENC-Validation-Checks#24]
Proposal from AHO – (see ENCWG4-05.25)
[ENCWG4_2019_5.25_Omnidirectional_LongRangeLigths.pdf](https://github.com/iho-ohi/ENCWG-S58-ENC-Validation-Checks/files/5116817/ENCWG4_2019_5.25_Omnidirectional_LongRangeLigths.pdf)
[New S58-Check for absent centre point for 10M LIGHTS.docx](https://github.com/iho-ohi/ENCWG-S58-ENC-Validation-Checks/files/5116819/New.S58-Check.for.absent.centre.point.for.10M.LIGHTS.docx)

**Comment by FrankHippmann** [comment]
Agree, however, the proposal states, "A new S-58 check (Warning) should be created...", but the Cat column is listed as C.

**Comment by IngaFjellanger** [comment]
Navico agrees. We have also noted the same as Frank, that if this should be a warning, we need W in Cat column.

**Comment by alvarosanuy** [comment]
It should be a WARNING not a CRITICAL error.

**Comment by TomRichardson6** [comment]
Agree as a warning, note that existing errors can highlight this issue but a specific check is preferred. Given the reference to aid to navigation structure object, if this refers to a specific list of objects that should be included in S-58 potentially by reference to the UOC. This will improve consistency.

**Comment by JeffWootton** [comment]
Agree with all the above.  Wording also needs to be tidied up - it looks like there is a missing "AND" after "Not Present".
Question:  If an all-around light with an unknown structure object also has another slave object (such as a radar reflector or fog signal), such that the light is designated as the master object in the relationship, would this still fail the proposed new Check?

**Comment by FrankHippmann** [comment]
> Question: If an all-around light with an unknown structure object also has another slave object (such as a radar reflector or fog signal), such that the light is designated as the master object in the relationship, would this still fail the proposed new Check?

Yes, the check as currently proposed would still fail. But, as your comment implies, the centre point of the LIGHTS location is now visible on the ECDIS display. The check could be modified to not trigger if there is another equipment object at the same location:

For each omnidirectional LIGHTS feature object where CATLIT doesn't contain 5 (aero light) or 6 (air obstruction light) AND LITCHR is not Equal to 12 (morse) AND VALMNR >= 10, which is COVERED_BY a LNDARE AND not EQUALS a navigational aid structure **or equipment** feature object as a master.

**Comment by Christian-Shom** [comment]
Agree with Frank last wording. We may consider adding values 1 and 16 for CATLIT as in the original proposal (it's not in the UOC but it makes sense).
If we add a defintion of an omnidirectional light in S-58 (1.4.3?) a reference to that definition should be made in the check.

**Comment by FrankHippmann** [comment]
The reason why I recommend not adding values 1 and 16 for CATLIT is as follows.

1. The origin of this issue is the S-52 LIGHTS06 conditional symbology procedure (CSP), so the definition should match that of S-52. S-52 has the precise definition, not the UOC.
2. Having a 360 degree sector LIGHTS with CATLIT equal to 1 or 16 is an invalid encoding that is reported by S-58 check 1778.
3. The centre point of a 360 degree sector LIGHTS with CATLIT equal to 1 or 16 is not visible.

To avoid confusion, I recommend that a reference to S-52 Annex A, CSP LIGHTS06 be given for this S-58 check.

**Comment by LARRIVEEJCANADA** [comment]
Agree with the proposal and agree with Frank last wording and add as a warning.
