### ISSUE TITLE
S-58 New checks for illogical inter-tidal areas

### ISSUE THREAD

**Issue by iho-ohi** [iho-ohi/ENCWG-S58-ENC-Validation-Checks#25]
Proposal from Nautical Dimensions
[New S58-Check for illogical intertidal areas.docx](https://github.com/iho-ohi/ENCWG-S58-ENC-Validation-Checks/files/5116837/New.S58-Check.for.illogical.intertidal.areas.docx)
[ENCWG4_2019_5.11_EN_Consistent Use of Vertical Reference Datums in ENCs_V1.pdf](https://github.com/iho-ohi/ENCWG-S58-ENC-Validation-Checks/files/5116840/ENCWG4_2019_5.11_EN_Consistent.Use.of.Vertical.Reference.Datums.in.ENCs_V1.pdf)

**Comment by FrankHippmann** [comment]
Agree

**Comment by alvarosanuy** [comment]
**The recommendation of the ENCWG4_2019_5.11 paper is:** _Amend S-58 with the modified check 2000 and the additions of checks A, B, C1 and C2._
**BUT** the attached document _'New S58-Check for illogical intertidal areas.docx'_ does only show 2 amendments (C1 & C2) to S-58 instead of 4 as proposed in the ENCWG5 paper.
Please confirm if we are approving 2 or 4 changes.

**Comment by FrankHippmann** [comment]
The check 2000 amendment is included in issue #23.
I have included an additional document to issue #23 that references Check A and Check B (the logical equivalent of check 2000 for DSPM.VDAT and DSPM.SDAT).

**Comment by TomRichardson6** [comment]
Support checks C1 and C2 as in the original paper noting other checks are covered in other Issues.

**Comment by IngaFjellanger** [comment]
Navico supports checks C1 and C2

**Comment by JeffWootton** [comment]
Agree with the first proposed new Check.
For the second Check:  Please let me know if there is something I have missed here, but this Check seems to me to be a sub-set of the first proposed new Check; or is this Check supposed to be checking for values populated for a "mean sea level" datum (note that I disagree with the use of this term here as "Mean water level" does not have to be in reference to the sea), but a different vale of the 3 listed is used for sounding and vertical datums (if this is at all logical)?

**Comment by FrankHippmann** [comment]
The intent of C2 is to check for examples like:

Vertical Datum: Mean water level
Sounding Datum: Mean sea level

**Comment by alvarosanuy** [comment]
I support C1 BUT in regards to C2,

Are we saying that we need check C2  beacuse:

**'Mean sea level''(3)** = The average height of the surface of the sea at a tide station for all stages of the tide over a 19-year period, usually determined from hourly height readings measured from a fixed predetermined reference level.
**'Approximate mean sea level' (19)** = An arbitrary level, usually within 0.3m from that of Mean Sea Level (MSL).
**'Mean water level' (26)** = The average of all hourly water levels over the available period of record.

are all the same thing (a Mean sea Level datum) but named differently ??? 

Where is this documented? Should we make this call?

**Comment by FrankHippmann** [comment]
The three datums are different. The idea was that _Approximate mean sea level_ and _Mean water level_ approximate _Mean sea level_. However, depending on the timing of observations, _Mean water level_ could deviate from _Mean sea level_ substantially. Also, take into account Jeff's comment regarding _Mean water level_ not needing to reference the sea.

With reference to Jeff and Alvaro's comments, the legitimacy/correctness of C2 is up for debate.

**Comment by LARRIVEEJCANADA** [comment]
Agree with that checks for more accuracy concistency.
