### ISSUE TITLE
S-58 New check for overlapping M_VDAT objects

### ISSUE THREAD

**Issue by iho-ohi** [iho-ohi/ENCWG-S58-ENC-Validation-Checks#26]
Proposal from Navico
[New S58-Check for overlapping M_VDAT.docx](https://github.com/iho-ohi/ENCWG-S58-ENC-Validation-Checks/files/5116844/New.S58-Check.for.overlapping.M_VDAT.docx)

**Comment by FrankHippmann** [comment]
Agree

**Comment by FrankHippmann** [comment]
Disagree. This is already in S-58 6.1.0 as check 1507.

**Comment by alvarosanuy** [comment]
Agree with Frank. Check already exists and the wording is exactly the same  ...... we may be missing something here.

**Comment by TomRichardson6** [comment]
Do not support this check as proposed, as noted it duplicates 1507.

**Comment by Christian-Shom** [comment]
Agree with previous comments (already done with 1507).

**Comment by JeffWootton** [comment]
Agree that this is a duplication of Check 1507.

**Comment by LARRIVEEJCANADA** [comment]
Not agree as it is a duplication.
