### ISSUE TITLE
S-58 New Check for SCAMIN on the components of collection objects 

### ISSUE THREAD

**Issue by iho-ohi** [iho-ohi/ENCWG-S58-ENC-Validation-Checks#29]
Proposal from IC-ENC– (see ENCWG4-05.8)
An IC-ENC member has recently highlighted that there is no specific S-58 check for SCAMIN consistency on collection objects.

[New S58-Check SCAMIN.docx](https://github.com/iho-ohi/ENCWG-S58-ENC-Validation-Checks/files/5116882/New.S58-Check.SCAMIN.docx)
[ENCWG4_2019_5.8_SCAMINonAggregations_v1.pdf](https://github.com/iho-ohi/ENCWG-S58-ENC-Validation-Checks/files/5116887/ENCWG4_2019_5.8_SCAMINonAggregations_v1.pdf)

**Comment by FrankHippmann** [comment]
Agree

**Comment by alvarosanuy** [comment]
We have scenarios where the front lead (structure + equipment) is turned off  earlier (lower SCAMIN value) than the rear mark and the associated NAVLNE/RECTRC. This is in line with accepted chart generalisation practices and in agreement with AUOC section 2.2.7.1 clause 2. 
The introduction of this check would generate an 'erroneous' Error message that we should ignore. It would be better if this check can be written (and coded) in a way that accepts situations where at least one of the Master/Slave relationships in the C_AGGR has the same SCAMIN value than NAVLNE and RECTRC but not necessarily all of them.

**Comment by Christian-Shom** [comment]
My view is that both the proposal and Alvaro's comment make sense. I would suggest keeping the suggested checks but changing the fisrt one to "Warning".

**Comment by Christian-Shom** [comment]
My view is that both the proposal and Alvaro's comment make sense. I would suggest keeping the suggested checks but changing the fisrt one to "Warning".

**Comment by Christian-Shom** [comment]
My view is that both the proposal and Alvaro's comment make sense. I would suggest keeping the suggested checks but changing the fisrt one to "Warning".

**Comment by Christian-Shom** [comment]
My view is that both the proposal and Alvaro's comment make sense. I would suggest keeping the suggested checks but changing the fisrt one to "Warning".

**Comment by Christian-Shom** [comment]
My view is that both the proposal and Alvaro's comment make sense. I would suggest keeping the suggested checks but changing the fisrt one to "Warning".

**Comment by Christian-Shom** [comment]
My view is that both the proposal and Alvaro's comment make sense. I would suggest keeping the suggested checks but changing the fisrt one to "Warning".

**Comment by Christian-Shom** [comment]
My view is that both the proposal and Alvaro's comment make sense. I would suggest keeping the suggested checks but changing the fisrt one to "Warning".

**Comment by TomRichardson6** [comment]
I accept the logic in Alvaro's proposal but feel that would require the UOC to be changed, to be consistent. Although table 2.3 is only a recommended policy it is widely observed and those producers with specific SCAMIN policies can ignore the warning. Checks 1153 and 1554a/b also set the precedent that S-58 should reflect this recommended policy. Both checks were originally proposed to be warnings, so content for the second to be an error if that is agreeable to all.

**Comment by IngaFjellanger** [comment]
We in Navico are not sure that we should constrain the flexibility of SCAMIN usage. Specially it refers to the second proposed check. According to UOC 2.2.7.1 objects included in TSS should not have SCAMIN value. However navigational aids can be part of a TSS aggregation. In this case we will have either to set SCAMIN for TSS area objects or remove SCAMIN for navigational aids. Another way is not including navigation aids in the  TSS aggregation. None of these solutions are quite good for ENC presentation.

**Comment by Richard-Fowle** [comment]
Whilst I agree in principle to these new checks, Inga has a valid point, in addition the opening paragraph of UOC 2.2.7.1 "states while the procedure described below to determine the SCAMIN value for feature objects in an ENC cell is recommended, the SCAMIN values used are at the discretion of the Producing Authority." I therefore feel that both checks should be classified as 'warning'

**Comment by JeffWootton** [comment]
I can see the points raised in all the arguments presented above.  In regard to Tom's comment, the reference for Checks 1153 and 1154 is UOC clause 2.2.7, which prohibits the use of SCAMIN on Meta and Group 1 features - I therefore feel that there is a problem with these features appearing in table 2.5 with a SCAMIN Step value of NOT SET.  I would recommend that the table needs to be amended to either remove all the Group 1 and Meta features from the table; or the SCAMIN Step value amended for these features to something similar to "SCAMIN Prohibited".
I would also like to point out Note 4 of clause 2.2.7.1 of the UOC, just above table 2.5, which states that all the elements comprising a range system "must" have the same SCAMIN value.  While acknowledging that the introductory paragraph in clause 2.2.7.1 states that the policy is recommended, I have a problem with the use of the word "must" here (and also taking into account Alvaro's comment regarding aids leading marks in a range system above).  I suggest that this should be changed to "should" in the UOC to avoid confusion.
Finally, regarding these proposed checks:  Taking into account all the arguments above, with the additional comment that I am concerned about "opening the door" for similar checks regarding other recommended aggregations in the UOC (measured distances (C_AGGR is mandatory), mooring trots, Two-Way Routes, ...), I would like to suggest not including these Checks in S-58.  If the decision is to include these Checks, I recommend that they are both categorized as Warnings.  I would also expect then that it will only be a matter of time before a bunch of new checks are proposed, particularly in regard to measures such as Two-Way Routes and Archipelagic Sea Lanes.

**Comment by Christian-Shom** [comment]
Agree with Jeff that we have quite a amount of "must"should" inconcistencies in the UOC with regard to SCAMIN.
Like Inga, I am of the opinion that we should leave flexibility to the encoders (except for Group1, meta-objects and master-slave).
Consequently, I join Jeff's advice not to add the proposed checks.

**Comment by LARRIVEEJCANADA** [comment]
I agree with Christian's idea.  Leaving flexibility for the encoders would be my preference for objects other than critical objects.
