### ISSUE TITLE
Proposal to downgrade check 1778

### ISSUE THREAD

**Issue by Richard-Fowle** [iho-ohi/ENCWG-S58-ENC-Validation-Checks#30]
Proposal fro SHOM
Check 1778 first appeared in S-58 Edition 2.0 (2003), with a classification of Warning. It was "upgraded" from Warning to Error as part of the introduction of the new Critical classification for S-58 Edition 5.0.0 (2014). No justification of this upgrading has been found by the IHO Secretariat.
There is no precise guidance in S-4 and the UOC on what defines a directional lights in terms of sector arc length and HOs surely have different approaches. Thus, it cannot be considered that different encodings would degrade the quality of an ENC.
As a consequence, it is proposed to downgrade check 1778 to « Warning ».
[S-58 Check 1778.docx](https://github.com/iho-ohi/ENCWG-S58-ENC-Validation-Checks/files/5510768/S-58.Check.1778.docx)

**Comment by forodd** [comment]
we agree to check 1778 being downgraded to a warning

**Comment by JeffWootton** [comment]
I agree that this Check should be downgraded to Warning.

**Comment by alvarosanuy** [comment]
Support downgrading to Warning.
I had a look at IALA's definitions and I couldn't find any guidance on maximum sector arc length for directional lights either.

**Comment by LARRIVEEJCANADA** [comment]
Agree to downgrade this to a Warning instead of an Error.
