### ISSUE TITLE
Check 2000 RESTRN values for MARCUL

### ISSUE THREAD

**Issue by TomRichardson6** [iho-ohi/ENCWG-S58-ENC-Validation-Checks#32]
Check 2000 does not include the value 7 (Entry Prohibited) for RESTRN on the object MARCUL. Propose amend check 2000 to permit this value. Note that S-101 1.0.0 permits this value. Although check 2000 is only an error taking action may result in double encoding. In S-52 Preslib CSP RESTRN01 includes instructions for the value 7. 

Given recent discussions in the conversion sub working group a wider action to review check 2000 against the permitted values present in S-101 more generally may be appropriate.

**Comment by FrankHippmann** [comment]
I agree with Tom and can find no reference as to why RESTRN 7 shouldn't be an acceptable encoding.

**Comment by Christian-Shom** [comment]
Agree with adding value 7 for RESTRN on MARCUL in check 2000.

**Comment by Richard-Fowle** [comment]
Included in proposed draft edition 7.0.0 of S-58
