### ISSUE TITLE
Test 1536 - Not reporting when SOUACC on sounding 'degrades' overlying M_QUAL CATZOC

### ISSUE THREAD

**Issue by alvarosanuy** [iho-ohi/ENCWG-S58-ENC-Validation-Checks#34]
**Shouldn't a validation test report on soundings with a lower accuracy than that stated by CATZOC?**

Not sure the reason why test 1530 is not reporting soundings with SOUACC worse than charted ZOC. I believe it may be because, sometimes, we have to retain lower ZOC features that couldn't be disproved by new, higher ZOC, surveys (although similar thinking applies to 'least charted depths' over WRECKS, OBSTRN and UWTROC, and we have Tests like 1536, etc !!).
In those cases, we normally update the ZOC of the M_QUAL in the area but we may leave 1, 2 or 3 soundings from the previous survey. For example, a ZOC B survey can't disprove an existing ZOC C sounding (or least depth over a wreck, etc). In this case, the AHO retains the ZOC C sounding but encodes it as 'lower reliability depth' by populating QUASOU=4 and QUAPOS=4 (AUOC 5.3, Table 5.1 - Black text is national guidance - refer to attachment).

![image](https://user-images.githubusercontent.com/70189016/135936830-00b55f9a-d740-473c-95df-924b12415c9b.png)

I believe SOUNDG should have a test like WRECKS, UWTROC and OBSTRN that reports (ERROR) when QUASOU degrades the CATZOC value of the underlying M_QUAL object. Having said that, this test should ignore instances when the SOUNDG has QUASOU=4 & QUAPOS=4 (**if** AHO's approach is widely accepted and included in the UOC)

Also, my view is that Test 1530, **as is**,  could be a WARNING and not an ERROR (is about logical consistency - SOUACC  is unnecessary because CATZOC conveys **the same** info).

**Comment by Richard-Fowle** [comment]
Following discussion of the S-58 SubWG at ENCWG7 it was agreed to close this issue without action.
