### ISSUE TITLE
Changes to check 7 and 77

### ISSUE THREAD

**Issue by TomRichardson6** [iho-ohi/ENCWG-S58-ENC-Validation-Checks#35]
the paper below contains 2 proposals raised by IC-ENC to enhance S-58 they are;

To amend the wording of check 77 so specific scenarios do not report Critical errors.  

Expand the test data for check 7 to clarify the specific intent of this check and to avoid reporting valid encoding scenarios.

Your comments and feedback on these proposals would be welcomed the intent is to raise to the ENCWG at the meeting planned for Feb 15th-16th. 

[ENCWGXX_S-58 7.0.0 Change Proposals DRAFT.docx](https://github.com/iho-ohi/ENCWG-S58-ENC-Validation-Checks/files/7932396/ENCWGXX_S-58.7.0.0.Change.Proposals.DRAFT.docx)

**Comment by Richard-Fowle** [comment]
I agree with the intent of the proposed change but think we should amend the new wording wording to read 'Instances where the point of intersection is a single intermediate vertex or node AND where one DEPCNT doesn't cross to the other side of the other DEPCNT, are excluded.

**Comment by Richard-Fowle** [comment]
Included in Edition 7.0.0 and revidsed test data

**Comment by Richard-Fowle** [comment]
Included in Edition 7.0.0 and revidsed test data
