### ISSUE TITLE
S-58 check 3

### ISSUE THREAD

**Issue by Richard-Fowle** [iho-ohi/ENCWG-S58-ENC-Validation-Checks#38]
Proposal to amend check 3 to better align with the guidance given in EB65 clarifying that the record identifier NAME (concatenation of the RCNM & RCID must be unique within a dataset (EN and all ER files):- see attached file 

[Proposed change to check 3.docx](https://github.com/iho-ohi/ENCWG-S58-ENC-Validation-Checks/files/11050321/Proposed.change.to.check.3.docx)

**Comment by alvarosanuy** [comment]
Supported

**Comment by FrankHippmann** [comment]
Agree with the proposal.

**Comment by JeffWootton** [comment]
Agree with the proposal.

**Comment by tdepuyt** [comment]
Agree with this proposal.

**Comment by Richard-Fowle** [comment]
Changes approved at ENCWG8 and incorporated into S-58 edition 8.0.0 for submission to HSSC
