### ISSUE TITLE
Check 2000

### ISSUE THREAD

**Issue by Richard-Fowle** [iho-ohi/ENCWG-S58-ENC-Validation-Checks#39]
Proposal to amend check 2000 to remove 3 (under reclamation) as an allowable value for the attribute CONDTN for the feature RAILWY
[Proposed change to check 2000.docx](https://github.com/iho-ohi/ENCWG-S58-ENC-Validation-Checks/files/11050488/Proposed.change.to.check.2000.docx)

**Comment by Christian-Shom** [comment]
Agree with the proposal.

**Comment by TomRichardson6** [comment]
IC-ENC supports this proposal.

**Comment by alvarosanuy** [comment]
Supported

**Comment by FrankHippmann** [comment]
Agree with the proposal.

**Comment by JeffWootton** [comment]
Agree with the proposal.  Is aligned with S-101.

**Comment by LeoKuzmin** [comment]
i4-insight supports the change. 
BTW Railway feature does not permit the 3rd value of the 'condition' attribute in S-101.
