### ISSUE TITLE
S-58 Check 61b - Allow for DRGARE & UNSARE to be acceptable underlying object for features with WATLEV = 3

### ISSUE THREAD

**Issue by iho-ohi** [iho-ohi/ENCWG-S58-ENC-Validation-Checks#4]
Proposal from SHOM &  AHO (see ENCWG5-11A)

The existence of ‘always underwater’ objects within an UNSARE or DRGARE should not be reported as an ERROR. The existence of, for example, UWTROC, WATLEV=3 within unsurveyed areas is fairly common and the existence of features such as foul ground obstructions within dredged areas, although maybe not that common, cannot be ignored. Hence, reporting a Validation error message in these scenarios produce a number of ‘false positives’ that have a negative impact on the confidence users allocate to error messages. 
The AHO proposes amending the wording of S-58’s ‘Check Description’ and ‘Check Message’
[ENCWG5_2020_11A_Amendments_to_ENC_ValidationChecks_FINAL.pdf](https://github.com/iho-ohi/ENCWG-S58-ENC-Validation-Checks/files/5108630/ENCWG5_2020_11A_Amendments_to_ENC_ValidationChecks_FINAL.pdf)
[S58-Check 61b.docx](https://github.com/iho-ohi/ENCWG-S58-ENC-Validation-Checks/files/5116340/S58-Check.61b.docx)

**Comment by FrankHippmann** [comment]
Agree. I would change the "Check message" to:

Point object where WATLEV = 3 (always underwater/submerged) is not covered by a suitable bathymetry object.

**Comment by IngaFjellanger** [comment]
Navico agrees

**Comment by TomRichardson6** [comment]
Agree

**Comment by alvarosanuy** [comment]
Supported.

**Comment by Richard-Fowle** [comment]
I propose the following wording :- 

For   each feature object of geometric primitive point where WATLEV is Equal to 3   (always underwater/submerged) which is not COVERED_BY a DEPARE feature object   (where DRVAL2 is Greater than 0)  AND is not COVERED_BY a DRGARE feature object AND is not COVERED_BY an UNSARE feature object, OR is COVERED_BY a LNDARE feature object of geometric primitive point or line.
--

**Comment by Christian-Shom** [comment]
Agree with Richard's wording for the check.
Agree with Frank's wording for the Check message.

**Comment by JeffWootton** [comment]
Agree, with amendments as recommended by Frank and Richard.
