### ISSUE TITLE
S-58 Check 1

### ISSUE THREAD

**Issue by Richard-Fowle** [iho-ohi/ENCWG-S58-ENC-Validation-Checks#40]
Whilst check 1 checks for edges that are coincident with another edge there is currently no check to identify edges that overlap themselves therefore it has been proposed to amend check 1 to identify such instances:-
[Proposed change to check 1.docx](https://github.com/iho-ohi/ENCWG-S58-ENC-Validation-Checks/files/11050619/Proposed.change.to.check.1.docx)

**Comment by Christian-Shom** [comment]
In S-58, 2.4, "Coincident" is described as similar to "overlap" when comparing 2 geometric lines.
Moreover, "Line segment" is not defined in the current version of S-58.
I personally do not see the improvement that would be brought by the proposal, as if two line segment overlap, two edges will be coincident.
But I may have missed something...
A figure would be useful to better understand the issue.

**Comment by FrankHippmann** [comment]
To Christian's point, "Moreover, "Line segment" is not defined in the current version of S-58."

The term line segment has a mathematical definition: _a section of a line bounded by two points_. I don't see a problem in adding this definition to S-58.

The current issue with check 1 is that it only reports if a segment of an edge is coincident with another segment of a **different** edge. It doesn't report if two segments of the **same** edge are coincident.

I think that Mikus' proposed wording captures the intent of the check, but I also think that the use of the term edge is redundant, i.e., we only care if two segments are coincident. This takes care of all scenarios: full edge coincident with another edge, part of an edge coincident, only one segment coincident with another segment, ... We should aim to specify the check as succinctly as possible. Having said that, I would still accept Mikus' proposed updates to the wording if people feel that it is clearer and easier to understand.

In any case the meaning should be consistent with S-57 Part 2 2.2.1.2, "Duplication of coincident linear
geometry is prohibited.".

**Comment by alvarosanuy** [comment]
> The term line segment has a mathematical definition: _a section of a line bounded by two points_. I don't see a problem in adding this definition to S-58

Happy to approve the intent of the amendment and agree a definition of 'Line segment' is required in S-58. I would replace the word 'points' with 'vertices' though.

**Comment by JeffWootton** [comment]
I note that there are currently 88 instances of the use of the word "edge" in S-58 (and no instances of "line segment").  Therefore, as I see it, there are 2 options:
1) Include a definition for the term "edge" (_a section of a line bounded by two vertices_) in the Introductory section of S-58.  No other change required.
2) Amend Check 1 as included in the proposal; include definition for "line segment" in the Introductory section of S-58; evaluate all other instances of the use of the term "edge" throughout S-58 and amend as required.

Personally I prefer option 1 as this requires the least change in S-58.

In regard to already recognized terms and their definitions, we have already departed from these in S-58 with the definitions of Line and LineString, so I see no problem with simply defining "Edge" using essentially the same mathematical definition as for line segment.

I think that this will take care of all concerns raised so far, as "COINCIDENT" by definition includes OVERLAPS (an edge partially or completely overlapping another edge) as has been pointed out by others; and the "bounded by two vertices" takes care of Frank's point about 2 segments of the same edge being coincident - I don't think this can happen as, if I interpret this correctly, for this to occur the "edge" would have to have more than 2 vertices (would no longer be "the same" edge).

**Comment by FrankHippmann** [comment]
_I don't think this can happen as, if I interpret this correctly, for this to occur the "edge" would have to have more than 2 vertices (would no longer be "the same" edge)_

This is true for the mathematical definition of edge. However, I was using the S-57 definition of edge, i.e. "A one-dimensional spatial object, located by two or more coordinate pairs". Using this definition, an S-57 edge can contain multiple segments. This is also what S-58 means when it refers to "edge". Unfortunately, the problem is that S-57's definition of edge is very different to the mathematical (and more intuitive) definition of edge. This is one reason why the term edge was replaced with curve in S-100.

**Comment by LeoKuzmin** [comment]
I suppose that description of the check #1 is enough to check any cases of coincident edges. The definition and description spatial operator COINSIDENT in the clause 2.4 on the 8th page of S-58 fully describes all cases incorrect mutual position of two edges.
"Two geometric Lines OVERLAP or one geometric Line is WITHIN the other. Note that EQUAL Lines are also COINCIDENT by this definition."
Where operators OVERLAP, WITHIN and EQUAL mathematically unambiguously define mutual position of two edges.
If we insert the term "Line Segment" in this check, we will be obliged to create error message for each segment where two edges coincident. However, I believe, it will be redundant messages.
As regards a case where line itself creates partial overlap of its own edge ("tightened edge"), there is no specific check in S-58. For that we have special inner dKart checks. 
Our suggestion is:
- rename the 1st check to "1a" and keep without changes;
- add a new check 1b to look for "tightened edge".

**Comment by TDYCARHugh** [comment]
2.2.1.2 says "Duplication of coincident linear geometry is prohibited".

We have test 1 if that checks edges against other edges.

Perhaps we could just have a test that states that an edge which contains coincident linear geometry is invalid.

**Comment by tdepuyt** [comment]
What if we changed the language to something like - "For any edge that crosses or overlaps itself at point other than beginning or end node."

**Comment by MikusRL** [comment]
I trust that the "tolerance" makes this issue even more complicated with the geometries. Would there be a need to state in the checks that the standard cartographic tolerance (and define it in S-58) is or is not taken into account for this check. That especially is important for two objects captured almost side by side as in the bottom example of the drawing.
