### ISSUE TITLE
Direction light

### ISSUE THREAD

**Issue by Christian-Shom** [iho-ohi/ENCWG-S58-ENC-Validation-Checks#42]
Validation check 1778 detects lights encoded as directional, but for which the angle is more than 10 degrees.
![image](https://github.com/iho-ohi/ENCWG-S58-ENC-Validation-Checks/assets/71139640/84d3a5eb-65aa-42ac-8a05-4043e144f2e6)
Shom has found instances where ORIENT is Unknown and there is no associated NAVLNE and/or RECTRC and where SECTR1 and SECTR2 have no value, This encoding combination only seems « possible » when the sector limits are unknown, what is not a common situation. In our case, SECTR1 and SECTR2 were obviously missing.
I suggest renaming check 1778 to 1778a and creating a new check 1778b :
![image](https://github.com/iho-ohi/ENCWG-S58-ENC-Validation-Checks/assets/71139640/d2b68bb1-a0f9-47ee-99b6-2e5ced81e744)

**Comment by Christian-Shom** [comment]
Suggest changing the proposed check message to:
"Directional or moiré effect light with possible missing attribute values for SECTR1 and SECTR2 or for ORIENT."

**Comment by FrankHippmann** [comment]
The _Check description_ needs to explicitly state what is meant by "no values", i.e., one of:

_SECTR1 and SECTR2 are Unknown_

or

_SECTR1 and SECTR2 are Not Present_

or

_SECTR1 and SECTR2 are Not Present or Unknown_

**Comment by Christian-Shom** [comment]
Thanks Frank,
I think we should have: "SECTR1 and SECTR2 are Not Present or Unknown."
