### ISSUE TITLE
Check No 507 for LIGHTS object mandatory attributes

### ISSUE THREAD

**Issue by MikusRL** [iho-ohi/ENCWG-S58-ENC-Validation-Checks#43]
There is a situation where two major validation tools interpret 507 Critical S-58 check completely opposite in a specific case. We (PRIMAR validation team) would like to hear the S-58 SubWGs thoughts, if there could be suggested any appropriate action in the documentation to clarify this out (to check - if this is more clear in the S-101 documentation for the LIGHTS.).

Extract from S-57 Appendix B, Product Specifications:
![image](https://github.com/iho-ohi/ENCWG-S58-ENC-Validation-Checks/assets/72803214/e01a3915-e9e9-45ac-991e-0058974a3e5e)

Use case is for the CATLIT being encoded as Unknown and LITCHR not being encoded.  Some validation tools report Critical Error whereas others do not report anything. 

Reasoning for the producers encoding use case and for the validation software not to report this use case as critical at this stage are:
- From producer:
In our ENCs, many LIGHTS with STATUS=11 (extinguished) might never become lit again. Most of them are lights in small fishing harbors. Those extinguished lights remain on paper charts published by our Navy. Some of them are even in the light list. We have tried to 'check' and clean up some of those.
I understand that LITCHR is mandatory except for air obstruction light and fog detector light, and it could be set as unknown.
After doing some experiment, I found that 7Cs Analyzer does not report S-58 #507 (missing LITCHR) when the LIGHTS has CATLIT set as unknown.
[ If that unknown CATLIT is deleted, S-58 #507 (missing LITCHR) will be reported as a critical error. ]
Of course that particular light should not be either an air obstruction light or a fog detector light.  
I'll add unknown LITCHR to it with another update. Although I do prefer that LITCHR and COLOUR are not mandatory for extinguished lights, and texts of those attributes are not displayed in case of extinguished lights.

- From 7Cs:
LITCHR is mandatory if it is known that the LIGHTS is not an air obstruction or fog detector light, but we don't know this. The producer has explicitly encoded CATLIT as unknown, meaning that the LIGHTS may be an air obstruction or fog detector light. Analyzer can therefore not make the assumption that the LIGHTS is not an air obstruction or fog detector. So there are three encodings where a LIGHTS may possibly be considered an air obstruction of fog detector:
1.    CATLIT = 6 (air obstruction light)
2.    CATLIT = 7 (fog detector light)
3.    CATLIT = unknown (may be air obstruction or fog detector or something else - we don't know)
We have had discussions quite a few years ago based on feedback (I cannot find them now) where we decided to only report missing mandatory attributes if the preconditions are met with certainty. Otherwise we will have support cases for the opposite scenario, i.e., Analyzer reports Critical missing mandatory attribute errors for feature objects that are open to interpretation based on unknown attribute values.

I hope that the group could suggest any appropriate update to the standards to be able to either harmonize the validation software development with less ambiguity or the producers get more descriptive encoding guidance in such a use case as above.

**Comment by Christian-Shom** [comment]
I can't see an ideal solution for this...
CATLIT is mandatory for air obstruction and fog detector lights, but this is impossible to check this as the condition is on the proper attribute.
I think the Product Specification should be interpreted as follows by the validation tool: 
"_COLOUR and LITCHR are mandatory for all lights, except when CATLIT contains values 6 or 7_". 
This would imply that if LITCHR does not contain one of these values (or is undefined or unknown), the light is neither air obstruction or fog detector.
Having said that, we can't change check 507!

**Comment by FrankHippmann** [comment]
I note the S-58 group's decision to have a critical error reported when LITCHR is missing and CATLIT is unknown.

Could I please confirm from the group the following behaviour based on the following analogous scenarios:

1. Report a critical error for a LIGHTS when SIGPER is missing and LITCHR is unknown.
2. Report a critical error for a LIGHTS when SIGGRP is missing and LITCHR is unknown.

That is, if LITCHR is unknown, then the LIGHTS is _not_ considered fixed.

From the ENC PS

![mand sigper siggrp](https://github.com/iho-ohi/ENCWG-S58-ENC-Validation-Checks/assets/70178466/cdf1def4-b011-4d3c-bcb3-dd80ff1716e5)

**Comment by Richard-Fowle** [comment]
Check 509 amended and the following footnote added '1 For air obstruction light and fog detector light CATLIT must be set to 6 or 7 respectively' changes incorporated into S-58 edition 8.0.0 for submission to HSSC
