### ISSUE TITLE
Revise check 1800

### ISSUE THREAD

**Issue by Christian-Shom** [iho-ohi/ENCWG-S58-ENC-Validation-Checks#49]
Due to decision 7/42 at ENCWG7 that a Transporter bridge is to be considered as a Fixed bridge, value 8 is to be removed in check 1800.
Also replace "Equal" by "contains" to detect all cases.
Proposal:
![image](https://github.com/iho-ohi/ENCWG-S58-ENC-Validation-Checks/assets/71139640/48cac391-4f84-4c67-846a-ecb0942f811f)

**Comment by Richard-Fowle** [comment]
Following discussions by ENCWG S-58 SubWG VTC on 28/08/2024 it was agreed to close this issue and open a new issue to find a consistent approach to checks that relate to list attributes that contain/include specific values.
