### ISSUE TITLE
S-58 Checks 507, 506 and 508b

### ISSUE THREAD

**Issue by iho-ohi** [iho-ohi/ENCWG-S58-ENC-Validation-Checks#8]
Proposal from AHO (ENCWG5-11A) amend current checks to avoid the absence of the attribute COLPAT triggering a 'Critical' error
[S58-Check 507, 508a & 508b.docx](https://github.com/iho-ohi/ENCWG-S58-ENC-Validation-Checks/files/5116375/S58-Check.507.508a.508b.docx)
[ENCWG5_2020_11A_Amendments_to_ENC_ValidationChecks_FINAL.pdf](https://github.com/iho-ohi/ENCWG-S58-ENC-Validation-Checks/files/5116376/ENCWG5_2020_11A_Amendments_to_ENC_ValidationChecks_FINAL.pdf)

**Comment by FrankHippmann** [comment]
Are there examples where a BCNXXX has multiple colours but no defined colour pattern? If this is the case, then I support the proposal. Otherwise, a Null value implies that the encoder recognises that COLPAT should be encoded, but he/she doesn't know what it is.

**Comment by TomRichardson6** [comment]
Agree

**Comment by alvarosanuy** [comment]
Support proposed changes

**Comment by JeffWootton** [comment]
I tend to agree with this proposal, but have an amendment and a concern:
Amendment:  Suggest leaving 508a unchanged and not introducing a new 508c.  COLPAT is mandatory for non-lights where COLOUR has more than one value; if the attribute is missing it does not comply with a mandatory requirement in the Product Specification, therefore such occurrences should at least be categorized as Error.
Concern:  Are there other similar situations where not populating a mandatory attribute, while not conforming with the Product Specification, has no impact on ECDIS display or performance?  If such is the case I can see more arguments being put forward to amend Check 507.

**Comment by Christian-Shom** [comment]
One remark first: I can't see "COLPAT is not present" in current check 507... (may be a lockdown colateral effect...).
Although I agree there is probably no issue with not populating COLPAT, I am not in favour of modifying a check and allow an encoding to not conform with the Product Specification. I'm sure there are many other cases like this one and we may be opening a breach...

**Comment by TDYCARHugh** [comment]
I cannot find any reference to COLPAT in S-52. Is it used by Mariners in pick reports?  I am wondering why a missing COLPAT would be any higher than a warning.

**Comment by LARRIVEEJCANADA** [comment]
If it is not a critical information I am not agree with this change.  What is the value of this? Critical Error is excessive. Should be a warning.
